pass-through:
- water
- lava
- grass
- fern
- tall_grass
- large_fern
- dead_bush
- vine
- cave_air
descend-speed: 5
model:
  base:
    glass:
      block-type: glass
      from: -2, 0, -2
      to: 2, 0, 2
  tools:
    enderchest:
      block-type: ender_chest
      at: -2, 0, 0
    workbench:
      block-type: crafting_table
      at: 2, 0, 0
  light:
    glowstone:
      block-type: glowstone
      at: 0, 0, 0
